#!/bin/bash

# let us evaluate which branch we are working with.
GIT_BRANCH_GOT=`echo ${2} | cut -d "/" -f2 | tr '[:upper:]' '[:lower:]'`
echo "SIMPRAGMA: Jenkins running for BRANCH=${GIT_BRANCH_GOT}"

# let us switch to specific branch
test "${GIT_BRANCH_GOT}" == "master" &&
{
	echo "SIMPRAGMA: BRANCH=master is choosen for this build"
	# Write your branch specific build code here
}

test "${GIT_BRANCH_GOT}" == "develop" &&
{
	echo "SIMPRAGMA: BRANCH=develop is choosen for this build"
	# Write your branch specific build code here
}

test "${GIT_BRANCH_GOT}" == "feature" &&
{
	echo "SIMPRAGMA: BRANCH=feature is choosen for this build"
	# Write your branch specific build code here
}
mvn clean install
